app            = 'quantify-14hippos'
primary_region = 'sea'
swap_size_mb   = 512

[build.args]
  DATABASE_TYPE      = 'postgresql'
  ALLOWED_FRAME_URLS = 'https://curator.ninja http://curator.local:4000'

[http_service]
  internal_port        = 3000
  force_https          = true
  min_machines_running = 1
  processes            = ['app']

[[vm]]
  memory   = '256mb'
  cpu_kind = 'shared'
  cpus     = 1
